# 必填：网站基本设置
title: "Welcome!It's Weiheng's homepage"    # 浏览器标签页显示的标题
name: "Weiheng Wu"           # 你的名字
description: "PhD Student at UCAS" # 简短描述

# 必填：侧边栏设置 (Sidebar)
minimal_mistakes_skin: "default" # 保持默认即可

# 社交链接 (显示在侧边栏底部)
author:
  name   : "Weiheng Wu"
  avatar : "profile.png"    # 你的头像文件名 (稍后上传)
  bio    : "PhD student in CS, focusing on System Security." # 侧边栏简介
  location : "Beijing, China"
  email : "Weiheng Wu@university.edu"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/wudaoz"
    - label: "Google Scholar"
      icon: "ai ai-google-scholar" # 学术图标
      url: ""